import type { NextPage } from "next";
import Image from "next/image";
import { useRef } from "react";
import Head from "next/head";
import {
  AiFillGithub,
  AiFillInstagram,
  AiOutlineWhatsApp,
} from "react-icons/ai";
import { IoIosArrowDown } from "react-icons/io";
import SectionHeading from "../components/SectionHeading";
import Technology from "../components/Technology";
import Tech from "../utils/data";
const Home: NextPage = () => {
  const ref = useRef<null | HTMLDivElement>(null);

  const handleClick = () => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };
  const name = "<Web Vikasaks/>";
  return (
    <>
      <Head>
        <title>Web Vikasaks</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ----------------------------INTRO SECTION---------------------- */}

      <section id="1" className="h-fit flex flex-col section1_bg">
        <div className="h-screen flex flex-col justify-center items-center z-0">
          <Image
            src="/wvName.png"
            alt="Picture of the author"
            width={750}
            height={150}
          />
          <p className="text-2xl text-textColor p-4 text-center">
            Are you a web developer looking for a supportive community to share
            your ideas and collaborate with like-minded professionals. <br />
            Join our community of developers.
          </p>
          <div className="p-6 z-0">
            <a href="https://github.com/akashag55/WebVikasak-S" className="m-4">
              <button className="btn btn-outline">
                <AiFillGithub className="h-6 w-6" />
              </button>
            </a>
            <a
              href="https://chat.whatsapp.com/BtUipYfE04QCbBVNU1DmD8"
              className="m-4"
            >
              <button className="btn btn-outline">
                <AiOutlineWhatsApp className="h-6 w-6" />
              </button>
            </a>
          </div>
        </div>
        <div className="flex flex-col justify-center items-center mb-5">
          <a href="#section2">
            <button
              className=" btn btn-circle btn-outline"
              onClick={handleClick}
            >
              <IoIosArrowDown />
            </button>
          </a>
        </div>
      </section>

      {/* ----------------------------ABOUT SECTION---------------------- */}

      <section id="" ref={ref} className="h-fit flex flex-col section1_bg">
        <div className=" flex flex-col justify-center item-center p-4 z-0">
          <SectionHeading title="ABOUT US" />
          <div className="container mx-auto">
            <div className="">
              <div className="flex flex-col-reverse sm:flex-row justify-evenly mt-20">
                <div>
                  <p className="pb-4 pl-5 font-semibold text-2xl">
                    what we do..
                  </p>
                  <div className="px-10 py-5">
                    <ul className="leading-8">
                      <p className="list-disc">
                        We Build custome websites that are tailored to your
                        unique business needs and goals.
                      </p>
                      <p className="list-disc">
                        We are also building a community for all the developers
                        and creators around the glob.
                      </p>
                    </ul>
                  </div>
                </div>
                <div className="contents">
                  <Image
                    src="/undraw_in_sync_re_jlqd.svg"
                    alt="Picture of the author"
                    width={350}
                    height={200}
                  />
                </div>
              </div>
              <div className="flex flex-col sm:flex-row justify-evenly mt-20">
                <div className="contents">
                  <Image
                    src="/undraw_futuristic_interface_re_0cm6.svg"
                    alt="Picture of the author"
                    width={350}
                    height={200}
                  />
                </div>
                <div>
                  <p className="pb-4 pl-5 font-semibold text-2xl">
                    why we do..
                  </p>
                  <div className="px-10 py-5">
                    <ul className="leading-8">
                      <p className="list-disc">
                        To connect with a global audience & To foster community
                      </p>
                      {/* <p className="list-disc">To foster community</p> */}
                    </ul>
                  </div>
                </div>
              </div>
              <div className="flex flex-col-reverse sm:flex-row justify-evenly mt-20">
                <div>
                  <p className="pb-5 pl-5 font-semibold text-2xl">
                    how we do..
                  </p>
                  <div className="px-10 py-5">
                    <ul className="leading-8">
                      <p className="list-disc">
                        We use latest technologies and techniques to ensure that
                        your website is fast, secure and user-friendly.
                      </p>
                    </ul>
                  </div>
                </div>
                <div className="contents">
                  <Image
                    src="/undraw_community_re_cyrm.svg"
                    alt="Picture of the author"
                    width={350}
                    height={200}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ----------------------------SKILLS SECTION---------------------- */}
      <section className="h-fit flex flex-col justify-center item-center section1_bg">
        <div className="z-0">
          <SectionHeading title="Technologies we work On" />

          <Technology />
          {/* <div>
            {Tech.map((item: any, index: number) => (
              <Technology
                key={index}
                src={item.src}
                alt={item.alt}
                name={item.name}
                imageClassname="relative h-25 w-25"
                className="flex gap-5 p-4 "
              />
            ))}
          </div> */}
        </div>
      </section>

      {/* ----------------------------DEVELOPER SECTION---------------------- */}

      <section className="h-screen flex flex-col justify-center item-center section1_bg">
        <div className="z-0">
          <SectionHeading title="OUR TEAM" />
          <div className="flex justify-around items-center gap-10">
            <div>
              <div className="border border-grey-200 w-40 h-40 rounded-full">
                <Image
                  className="border border-grey-200 w-40 h-40 rounded-full"
                  src="/aashish.jpg"
                  alt="Short Lofo"
                  width={250}
                  height={250}
                />
              </div>
              <div className="flex flex-col items-center item-center">
                <p>Aashish Singhal</p>
                <p>Founder and Developer</p>
              </div>
            </div>
            <div>
              <div className="border border-grey-200 w-40 h-40 rounded-full">
                <Image
                  className="border border-grey-200 w-40 h-40 rounded-full"
                  src="/akash.png"
                  alt="Short Lofo"
                  width={250}
                  height={250}
                />
              </div>
              <div className="flex flex-col items-center item-center">
                <p>Akash Agarwal</p>
                <p>Founder and Developer</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <footer className="footer items-center p-4 border-t-2 text-content section1_bg">
        <div className="flex justify-between items-center z-0 w-full">
          <div className="w-12 h-5 relative">
            <Image
              width={20}
              height={20}
              layout="fill"
              className="-rotate-12"
              src="/logo_initials.png"
              alt="Short Lofo"
              style={{ objectFit: "contain" }}
            />
          </div>
          <p>Copyright © 2022 - All right reserved</p>
        </div>
        {/* <div className="grid-flow-col gap-4 md:place-self-center md:justify-self-end z-0">
          <a href="https://github.com/WebVikasak-S">
            <AiFillGithub className="h-6 w-6" />
          </a>
          <a>
            <AiFillInstagram className="h-6 w-6" />
          </a>
        </div> */}
      </footer>
    </>
  );
};

export default Home;
